### ISSUE TITLE
electron-quick-start install failure

### ISSUE THREAD

**Issue by veleek** [electron/electron-quick-start#106]
I'm running into an error when trying to install the quickstart:

> npm-debug.log: https://gist.github.com/veleek/dccef7d86f4143ef917faf36afc0a54e

Console output below

```
PS C:\src\github\electron\electron-quick-start> npm install

> electron@1.4.6 postinstall C:\src\github\electron\electron-quick-start\node_modules\electron
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\src\github\electron\electron-quick-start\node_modules\single-line-log\index.js:12:16)
    at process.<anonymous> (C:\src\github\electron\electron-quick-start\node_modules\single-line-log\index.js:17:29)
    at emitOne (events.js:101:20)
npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\github\electron\electron-quick-start\npm-debug.log
```

**Comment by MarshallOfSound** [comment]
Node.JS 7.1.0 has some issues installing and using certain packages.  I would recommend sticking to LTS versions of node (v4 or v6) if you want a stable experience 👍

**Comment by veleek** [comment]
Yeah, after a bunch more searching I was able to figure out that the problem was with node. :(  Fixed, but annoyed.

**Comment by zeke** [comment]
Thanks for the extra info @veleek 👍
