### ISSUE TITLE
npm install fails on Windows 7

### ISSUE THREAD

**Issue by mraak** [electron/electron-quick-start#125]
Here's the error.

```bash
> electron@1.4.15 postinstall E:\dev\projects\nodeprojects\electron\electron-quick-start\node_modules\ele
ctron
> node install.js

E:\dev\projects\nodeprojects\electron\electron-quick-start\node_modules\electron\install.js:46
  throw err
  ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "i"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\dev\projects\nodeprojects\electron\electron-quick-start\npm-debug.log

```

**Comment by normeno** [comment]
@mraak I solved this error updating NodeJs

**Comment by mraak** [comment]
As you can see I got latest LTS version (v6.9.4). I also tried with v7.4.0 and got the same.

**Comment by imvetri** [comment]
@normeno could you share to which version you updated your node to?

**Comment by victorhsn** [comment]
maybe this [#6916](https://github.com/npm/npm/issues/6916) issue can help you.

**Comment by codebytere** [comment]
This will be remedied by updating your version of Node; i'm going to go ahead and close this issue but if you still find yourself experiencing issues with the most recent version of `electron-quick-start` and updated node we can certainly reopen this!
