### ISSUE TITLE
Fails to start, raspberry pi  'electron .'.

### ISSUE THREAD

**Issue by lycrake** [electron/electron-quick-start#128]
Hi there

Trying to get this to work...

I've installed the most recent version of nodejs (7.5.0)
The installation of electron-quick-start seemed to go ok. 

Whenever I try and npm start I get the below error

npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.

> npm ERR! Linux 4.4.38-v7+
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v7.5.0
> npm ERR! npm  v4.1.2
> npm ERR! code ELIFECYCLE
> npm ERR! electron-quick-start@1.0.0 start: `electron .`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron .
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron-quick-start
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron-quick-start
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/pi/catbotdev/electron-quick-start/npm-debug.log

I've removed node_modules and reinstalled, I've deleted the entire git as well, redownloaded and reinstalled, but I start get the above error.

Any ideas what I'm doing wrong?

This is from the log file

> 2 info using npm@4.1.2
> 3 info using node@v7.5.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
> 6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
> 8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/no$
> 10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/catbotdev/electron-quic$
> 11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
> 12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
> 13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecy$
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:192:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.$
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:192:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:890:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid electron-quick-start@1.0.0

**Comment by lycrake** [comment]
This is from the log file as well

> 2 info using npm@4.1.2
> 3 info using node@v7.5.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
> 6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
> 8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/no$
> 10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/catbotdev/electron-quic$
> 11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
> 12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
> 13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecy$
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:192:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.$
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:192:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:890:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid electron-quick-start@1.0.0
>

**Comment by lycrake** [comment]
Right, I've solved my problem...!

I was being an idiot, I was still trying to launch it from an ssh session as opposed to terminal in the GUI....!

I'll leave this here for others just incase!
