### ISSUE TITLE
"cross platform" does not include BSDs

### ISSUE THREAD

**Issue by Martin-S-Weber** [electron/electron-quick-start#130]
```
Error: Failed to find Electron v1.4.15 for freebsd-x64 at https://github.com/electron/electron/releases/download/v1.4.15/electron-v1.4.15-freebsd-x64.zip
    at Request.<anonymous> ($SOMEWHERE/electron-quick-start/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at Request.onRequestResponse ($SOMEWHERE/electron-quick-start/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:189:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
npm ERR! FreeBSD 10.3-RELEASE-p11
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
```

Seeing the release artifacts, the above extends to at least NetBSD & OpenBSD (all of which have native chromium ports, btw).

**Comment by Martin-S-Weber** [comment]
Ok, thanks for the pointer, sorry for the duplicate.
