### ISSUE TITLE
electron-quick-start not working, errors during installation

### ISSUE THREAD

**Issue by D3V4N5H** [electron/electron-quick-start#135]
first, there were some error that recommended to delete node_modules/electron 
so i deleted that folder and installed again
installation successful.
now i tried
sudo npm start
and i'm getting following output:

> electron-quick-start@1.0.0 start /home/d/electron/electron-quick-start
> electron .

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/d/electron/electron-quick-start/npm-debug.log

[npm-debug.log.tar.gz](https://github.com/electron/electron-quick-start/files/797259/npm-debug.log.tar.gz)

**Comment by DevNIX** [comment]
Your problem seems related to your node installation: you may have the `nodejs` binary available, but not `node`. Try creating a symbolic link :)

```
/usr/bin/env: ‘node’: No such file or directory
```

**Comment by Dmitry1987** [comment]
I got this on windows, on first steps, just npm install and start:

```
Error: ENOENT: no such file or directory, lstat 'C:\mydata\electron\electron-quick-start\node_modules\electron\dist\resources'
npm WARN Error: EPERM: operation not permitted, scandir 'C:\mydata\electron\electron-quick-start\node_modules\getpass\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\mydata\electron\electron-quick-start\node_modules\getpass\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\mydata\\electron\\electron-quick-start\\node_modules\\getpass\\node_modules' }
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dima.shmakov\AppData\Roaming\npm-cache\_logs\2017-04-30T12_31_58_642Z-debug.log
```


in the log last lines it shows similar:

```
20509 silly vacuum-fs quitting because other entries in C:\mydata\electron\electron-quick-start\node_modules
20510 silly vacuum-fs quitting because other entries in C:\mydata\electron\electron-quick-start\node_modules
20511 silly vacuum-fs quitting because other entries in C:\mydata\electron\electron-quick-start\node_modules
20512 silly rollbackFailedOptional Finishing
20513 silly runTopLevelLifecycles Finishing
20514 silly install printInstalled
20515 verbose stack Error: electron@1.6.6 postinstall: `node install.js`
20515 verbose stack Exit status 1
20515 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
20515 verbose stack     at emitTwo (events.js:106:13)
20515 verbose stack     at EventEmitter.emit (events.js:194:7)
20515 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
20515 verbose stack     at emitTwo (events.js:106:13)
20515 verbose stack     at ChildProcess.emit (events.js:194:7)
20515 verbose stack     at maybeClose (internal/child_process.js:899:16)
20515 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
20516 verbose pkgid electron@1.6.6
20517 verbose cwd C:\mydata\electron\electron-quick-start
20518 error Windows_NT 6.1.7601
20519 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
20520 error node v7.9.0
20521 error npm  v4.2.0
20522 error code ELIFECYCLE
20523 error errno 1
20524 error electron@1.6.6 postinstall: `node install.js`
20524 error Exit status 1
20525 error Failed at the electron@1.6.6 postinstall script 'node install.js'.
20525 error Make sure you have the latest version of node.js and npm installed.
```

any advice?     thx

**Comment by jwittner** [comment]
I'm seeing the same thing. 

`npm install` fails with:

```
14256 silly install printInstalled
14257 verbose stack Error: electron@1.6.6 postinstall: `node install.js`
14257 verbose stack Exit status 1
14257 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14257 verbose stack     at emitTwo (events.js:106:13)
14257 verbose stack     at EventEmitter.emit (events.js:191:7)
14257 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14257 verbose stack     at emitTwo (events.js:106:13)
14257 verbose stack     at ChildProcess.emit (events.js:191:7)
14257 verbose stack     at maybeClose (internal/child_process.js:886:16)
14257 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14258 verbose pkgid electron@1.6.6
14259 verbose cwd C:\Users\jowitt\Source\electron-quick-start
14260 error Windows_NT 10.0.14393
14261 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
14262 error node v6.10.2
14263 error npm  v3.10.10
14264 error code ELIFECYCLE
14265 error electron@1.6.6 postinstall: `node install.js`
14265 error Exit status 1
14266 error Failed at the electron@1.6.6 postinstall script 'node install.js'.
14266 error Make sure you have the latest version of node.js and npm installed.
14266 error If you do, this is most likely a problem with the electron package,
14266 error not with npm itself.
14266 error Tell the author that this fails on your system:
14266 error     node install.js
14266 error You can get information on how to open an issue for this project with:
14266 error     npm bugs electron
14266 error Or if that isn't available, you can get their info via:
14266 error     npm owner ls electron
14266 error There is likely additional logging output above.
14267 verbose exit [ 1, true ]
```

**Comment by gilbertowa** [comment]
To me, works following the steps:

1.     install electron global with command: npm install electron -g
2.     cd my electron-quick-start direction to install application: npm install
3.     start application: npm start

ref:  https://github.com/electron/electron-quick-start/issues/117, by aperson

**Comment by zeke** [comment]
It looks your installation failed. This should do the trick:

```sh
rm -rf node_modules
npm install
npm start
```

**Comment by paivacampos** [comment]
I´m using debian 8 32bits, and all answers of this post don´t solve =/

**Comment by zeke** [comment]
> I´m using debian 8 32bits

@paivacampos can you open a new issue with the specific errors you're seeing?

**Comment by indeveler** [comment]
https://github.com/rhysd/NyaoVim/issues/127#issuecomment-392573556
