### ISSUE TITLE
npm install… stalls at 'node install.js'

### ISSUE THREAD

**Issue by lukejanicke** [electron/electron-quick-start#136]
`npm install` stalls at `> node install.js`

```bash
~/Projects $ git clone https://github.com/electron/electron-quick-start
Cloning into 'electron-quick-start'...
remote: Counting objects: 231, done.
remote: Total 231 (delta 0), reused 0 (delta 0), pack-reused 231
Receiving objects: 100% (231/231), 38.35 KiB | 12.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.
~/Projects $ cd electron-quick-start
~/Projects/electron-quick-start $ npm install

> electron@1.4.15 postinstall /Users/lukejanicke/Projects/electron-quick-start/node_modules/electron
> node install.js

```

Stuck here. Nothing happening.

Already tried the following.

```bash
~/Projects $ rm -rf ~/.electron/
~/Projects $ rm -rf ~/.atom/
~/Projects $ npm cache clear
```

I have the latest version of Node and NPM (freshly installed).

If I try `npm start` in another Terminal window, I get the following.

```bash
~/Projects/electron-quick-start $ npm start

> electron-quick-start@1.0.0 start /Users/lukejanicke/Projects/electron-quick-start
> electron .

/Users/lukejanicke/Projects/electron-quick-start/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/Users/lukejanicke/Projects/electron-quick-start/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lukejanicke/Projects/electron-quick-start/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lukejanicke/Projects/electron-quick-start/npm-debug.log
~/Projects/electron-quick-start $ 
```

Here is **[npm-debug.log](https://gist.github.com/lukejanicke/3f77d0869902bd0246ab4f295bc3416f)**.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lukejanicke/Projects/electron-quick-start/node_modules/.bin:/usr/local/aria2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/Library/TeX/texbin
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /Users/lukejanicke/Projects/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd /Users/lukejanicke/Projects/electron-quick-start
17 error Darwin 16.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I tried deleting **node_modules/electron**, as instructed. But when I run `npm install`… it stalls again.

**Comment by lukejanicke** [comment]
Update:

Still not fixed but I updated Node from **v7.5.0** to **v7.6.0**.

**Comment by IamPr377y** [comment]
I ran npm with verbose setting and saw it downloading electron from amazon servers at the speed of dead snail.  It took 10 minutes to finish, but now everything works.

**Comment by lukejanicke** [comment]
Thanks! After running `npm install --verbose` I saw the slow download. I moved to a faster connection and it finished.
