### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by maxjf1** [electron/electron-quick-start#156]
i'm having problems installing project dependencies.

when i run npm install, it gets stuck. after several minutes, it jumps the script, but i can't use npm start.

it gets stuck running the node install.js script
[Here is a PRINT](
http://imgur.com/i2gKGTH) with the node and npm versions

**Comment by Autumnwater** [comment]
me too

**Comment by victorhsn** [comment]
Are you executing the command as administrator? Paste the message from console here.

**Comment by maxjf1** [comment]
yes i am
the message is there
http://imgur.com/gallery/MmiO0

**Comment by victorhsn** [comment]
Hey @maxjf1, are you using some proxy? or behind some firewall? I guess that you can configure the proxy at npm. But first of all, try it; 

`npm cache clean`
`npm config set registry http://registry.npmjs.org/`

**Comment by zzw918** [comment]
I have the same problem, and  the `npm cache clean ....` solution is no use. Why?

**Comment by Black-Alpha** [comment]
Got it working on Windows 10
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
---------------------------------------------------------------

1. Removed node_modules folder
2. npm install extract-zip --save-dev
3. npm install electron --save-dev
4. npm start

**Comment by tansuo1989** [comment]
**use:**
`var {app, BrowserWindow} = require('electron')`

**instead:**

const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

**Comment by tansuo1989** [comment]
You can try:
`npm i electron-prebuilt`

It works , though I don't know why !

**Comment by maxjf1** [comment]
@victorhsn no proxy.

**Comment by zhouLion** [comment]
## im in Chinese mainland,and using the proxy in win10. it outputs errors after i 'npm install' like these ->
```shell
Error: connect ETIMEDOUT 54.231.97.200:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by molethiaz** [comment]
Hi community,

this error is caused by Byte Order Mark (BOM) in the script file. Notepad++ can convert the file to utf-8 without BOM.

greetings
