### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by FengHaiSheng** [electron/electron-quick-start#173]
> electron@1.7.9 postinstall /Users/wubo/wubo/electron/first/node_modules/electron
> node install.js

/Users/wubo/wubo/electron/first/node_modules/electron/install.js:48
  throw err
  ^

Error: connect ETIMEDOUT 54.231.40.51:443
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

**Comment by FengHaiSheng** [comment]
使用cnpm解决，应该是网络的问题
