### ISSUE TITLE
ERROR: Cannot define class using reflection

### ISSUE THREAD

**Issue by hajime0213222** [electron/electron-quick-start#198]
Im making App by using [this webpage](https://hackernoon.com/a-guide-to-tdd-a-react-redux-todolist-app-part-1-b8a200bb7091)

I tried e2e-tests .but it didnt work....This program failed to start selenium server. How do I fix this....

npm-v :5.6.0
yarn-v :1.5.1
os -v :10.12.6

error is below

ERROR: Cannot define class using reflection
chrome
    at new RuntimeError (/Users/hajimenagasaka/my-react-todolist/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/hajimenagasaka/my-react-todolist/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/Users/hajimenagasaka/my-react-todolist/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/hajimenagasaka/my-react-todolist/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/hajimenagasaka/my-react-todolist/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-react-todolist@0.1.0 e2e-tests: `wdio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-react-todolist@0.1.0 e2e-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
