### ISSUE TITLE
npm install && npm start thru error

### ISSUE THREAD

**Issue by flik** [electron/electron-quick-start#212]
Here is the detail:

 ```bash
npm install && npm start

> electron-quick-start@1.0.0 start /home/m/electron-quick-start
> electron .

/home/m/electron-quick-start/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/m/electron-quick-start/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/m/electron-quick-start/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Linux 3.5.0-54-generic
npm ERR! argv "/home/m/nvm/versions/node/v5.7.1/bin/node" "/home/m/nvm/versions/node/v5.7.1/bin/npm" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

```

**Comment by codebytere** [comment]
@lucy0417 that issue is with your internet, see [linux manpages](http://man7.org/linux/man-pages/man3/errno.3.html) and @flik if you use the latest version of `electron-quick-start` and follow the instructions above it should work! Please feel free to follow up if you continue to experience issues :)
