### ISSUE TITLE
Something wrong with  electron-packager

### ISSUE THREAD

**Issue by zhangshuaidan** [electron/electron-quick-start#215]
When I begin packaging my project, I run this code `electron-packager ./ --platform=win32 --arch=ia32`, the packaging is success, but I open the .exe file in the project ,there are some error 
`Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\Users\user\Desktop\Demo\electron-serialport\electron-serialport-win32-ia32\resources\app\node_modules\serialport\build\Release\serialport.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\user\Desktop\Demo\electron-serialport\electron-serialport-win32-ia32\resources\app\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\user\Desktop\Demo\electron-serialport\electron-serialport-win32-ia32\resources\app\node_modules\serialport\lib\bindings.js:3:35)`
what should I do to solve them？？？

**Comment by codebytere** [comment]
This is an issue with `electron-packager` and not `electron-quick-start`, please open an issue there if you are still experiencing issues!

**Comment by malept** [comment]
It's unlikely an Electron Packager issue either. This looks like you need to use [electron-rebuild](https://github.com/electron/electron-rebuild) and/or run the correct arch for your system.
