### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by MartinWong-H** [electron/electron-quick-start#216]
Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Projects\electron-quick-start\node_modules\usb\src\binding\usb_bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\electron-quick-start\node_modules\usb\usb.js:5:38)
    at Object.<anonymous> (D:\Projects\electron-quick-start\node_modules\usb\usb.js:408:3)

excuse ,how can i solve this problem? thanks

**Comment by ealipio** [comment]
Specify more details, what is your O.S, node version and reproduction steps for that issue

**Comment by codebytere** [comment]
As there has been no response to the above question, i'm going to go ahead and close this. Happy to re-open with follow-up.
