### ISSUE TITLE
Quick Start Can't Use Debug

### ISSUE THREAD

**Issue by rKinson** [electron/electron-quick-start#271]
TypeError: Cannot read property 'on' of undefined
main.js:36
    at Object.<anonymous> (c:\Users\admin\Documents\vscode\traveller\gui\main.js:36:5)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by kenlassesen** [comment]
This morning electron went south... and I am getting the same error (it worked fine yesterday).
- Running from VS Code.

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (d:\github\electron-quick-start\main.js:36:5)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Did a fresh install 
"devDependencies": {
    "electron": "^4.1.4"
  }

Node: 10.5.3

**Comment by codebytere** [comment]
This should be resolved if you `rm -rf node_modules` and rerun.
