### ISSUE TITLE
ubuntu npm start error

### ISSUE THREAD

**Issue by uikoo9** [electron/electron-quick-start#288]
node and npm version
```shell
root@insistime-unbutu:/home/work/workspaces/test# node -v
v10.15.3
root@insistime-unbutu:/home/work/workspaces/test# npm -v
6.9.0
```

npm start error
```shell
root@insistime-unbutu:/home/work/workspaces/test# npm start

> electron-quick-start@1.0.0 start /home/work/workspaces/test
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-14T07_56_21_271Z-debug.log
````

log file
```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/work/workspaces/test/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/work/workspaces/test
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/work/workspaces/test
16 verbose Linux 4.18.0-18-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by sunqiLoveSnow** [comment]
same error....

**Comment by codebytere** [comment]
Are you sure you ran `npm install` prior to `npm start`?

**Comment by uikoo9** [comment]
> Are you sure you ran `npm install` prior to `npm start`?

```shell
root@insistime-unbutu:/home/work/workspaces/0_electron# lss
node_modules  index.html  main.js  preload.js  renderer.js  package.json  package-lock.json  LICENSE.md  README.md
root@insistime-unbutu:/home/work/workspaces/0_electron# npm i
audited 201 packages in 1.683s
found 0 vulnerabilities

root@insistime-unbutu:/home/work/workspaces/0_electron# npm start

> electron-quick-start@1.0.0 start /home/work/workspaces/0_electron
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-27T06_13_58_484Z-debug.log
root@insistime-unbutu:/home/work/workspaces/0_electron# 

```

**Comment by zhangdongdongzdd** [comment]
the same error

**Comment by AncalagonTheBlack** [comment]
Same Error

**Comment by mbigger** [comment]
same error , Centos 7 x64, who can solve this problem？

**Comment by roscoevanderboom** [comment]
I was having similar errors installing the quick-starter and starting some older electron projects. Then updated to electron latest. Fixed the issues. 

`sudo npm install electron@latest`

Good luck

**Comment by RsPlayer** [comment]
> I was having similar errors installing the quick-starter and starting some older electron projects. Then updated to electron latest. Fixed the issues.
> 
> `sudo npm install electron@latest`
> 
> Good luck

You don't need sudo to install npm and you should never do it, it will just install dependacies into the project folder

**Comment by roscoevanderboom** [comment]
thx for that. so we learn :)

**Comment by codebytere** [comment]
Closing as this seems to be resolved.

**Comment by roscoevanderboom** [comment]
thanks for the correction. so we learn

**Comment by maychine-fatima** [comment]
hello i did the latest version but its not working for me the same errors.
