### ISSUE TITLE
npm install,error

### ISSUE THREAD

**Issue by xuwuruoshui** [electron/electron-quick-start#330]
```
✔ Installed 1 packages
✔ Linked 81 latest versions
[1/2] scripts.postinstall electron@7.0.1 › @electron/get@1.6.0 › global-agent@2.1.5 › core-js@^3.3.3 run "node postinstall || echo \"ignore\"", root: "/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_core-js@3.3.6@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[1/2] scripts.postinstall electron@7.0.1 › @electron/get@1.6.0 › global-agent@2.1.5 › core-js@^3.3.3 finished in 128ms
[2/2] scripts.postinstall electron@^7.0.1 run "node install.js", root: "/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_electron@7.0.1@electron"
(node:7752) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/_@szmarczak_http-timer@1.1.2@@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
(node:7752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2/2] scripts.postinstall electron@^7.0.1 finished in 523ms
✔ Run 2 scripts
Recently updated (since 2019-10-29): 6 packages (detail see file /home/xuwuruoshui/workspace/web/electron/electron-quick-start/node_modules/.recently_updates.txt)
✔ All packages installed (86 packages installed from npm registry, used 12s(network 11s), speed 112.1kB/s, json 82(195.83kB), tarball 1.06MB)
```
I use `npm install`, it stops at `node install.js`
Later I used `cnpm`, although the installation was successful, but there are many errors, `npm start` can not be used

**Comment by xuwuruoshui** [comment]
The operating system is manjaro linux

**Comment by xuwuruoshui** [comment]
I am waiting for `npm install` to execute, it still throws an exception like the above code.

**Comment by zeroyls** [comment]
Same with issue #328 

Set the environment variables `npm_config_electron_mirror="https://npm.taobao.org/mirrors/electron/" and `npm_config_electron_custom_dir="7.0.0"` before `npm install`.

**Comment by xuwuruoshui** [comment]
I think using version 6 is the only solution.

> Same with issue #328
> 
> Set the environment variables `npm_config_electron_mirror="https://npm.taobao.org/mirrors/electron/"` and `npm_config_electron_custom_dir="7.0.0"` before `npm install`.

**Comment by zeroyls** [comment]
[https://electronjs.org/docs/tutorial/installation](https://electronjs.org/docs/tutorial/installation)


>You can use environment variables to override the base URL, the path at which to look for Electron binaries, and the binary filename. The url used by electron-download is composed as follows:

>url = ELECTRON_MIRROR + ELECTRON_CUSTOM_DIR + '/' + ELECTRON_CUSTOM_FILENAMECopy
For instance, to use the China mirror:

>ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"

In old version, the `customDir` in code is equal to `$VERSION` if you set custom mirror, so the composed url will be "https://npm.taobao.org/mirrors/electron/5.0.6/electron-v5.0.6-darwin-x64.zip"  (such as in macOS and version is 5.0.6). But in new version, the `customDir` in code is equal to `v$VERSION`,  the composed url will be [https://npm.taobao.org/mirrors/electron/v7.0.1/electron-v7.0.1-darwin-x64.zip](https://npm.taobao.org/mirrors/electron/v7.0.1/electron-v7.0.1-darwin-x64.zip) if you only set `ELECTRON_MIRROR`,  then you will download fail, because the right url is [https://npm.taobao.org/mirrors/electron/7.0.1/electron-v7.0.1-darwin-x64.zip](https://npm.taobao.org/mirrors/electron/7.0.1/electron-v7.0.1-darwin-x64.zip)  (has no `v`).

**Comment by ahojukka5** [comment]
So how this can be compiled. First impressions to electron are not so good if the first copy-paste example is not working out from the box.

**Comment by codebytere** [comment]
@ahojukka5 did you try it yourself? the above issue is specific to those needing a Chinese mirror.

**Comment by ahojukka5** [comment]
Yes, I tried myself. `npm install` hangs to post-install phase. I'm not in China.

**Comment by kymocode** [comment]
Same issue here. Not in china. Arm6 32bit

**Comment by zlrs** [comment]
Changing Election version to 6.0.0 in `package.json` solved this problem.

**Comment by Hugh03** [comment]
> Same issue here. Not in china. Arm6 32bit.
> npm cannot find a binary for version 6 on arm. No versions of 7 work for me

I referred to zeroyls's method and i got it。But i am in china。maybe you can find a mirror and do it。Or，you can download the mirror:https://github.com/electron/electron/releases/download/v7.1.5/electron-v7.1.5-darwin-x64.zip

**Comment by zlrs** [comment]
I guess he does not need a mmirror since he is not in China. maybe npm
just does not have a version 6 in Arm6 32bit platform. I don't know
how electron version system goes but maybe there is a version 5 or
version 4 works in this situation?

2019-12-18 1:08 GMT+08:00, Hugh Zhang <notifications@github.com>:

**Comment by vitjf** [comment]
Скачайте Outlook для Android<https://aka.ms/ghei36>
________________________________

**Comment by wangdetong** [comment]
Same with issue #328

Electron 6.0.0 version is OK
change the pacakge.json,delete node_modules folder and npm install agin

 "devDependencies": {
    "electron": "^6.0.0"
  }

**Comment by Zhwt** [comment]
> 
> 
> @ahojukka5 did you try it yourself? the above issue is specific to those needing a Chinese mirror for firewall issues Electron cannot control. You should not need that workaround.

That problem is not related to Chinese mirror or firewall, it's about electron-download's internal url compose logic. Moreover, the workaround is undocumented.

**Comment by caob1234** [comment]
![image](https://user-images.githubusercontent.com/6292358/74790195-df968100-52f1-11ea-8c31-aa7ed00a3e43.png)

**Comment by bzr2004** [comment]
$cnpm intall
✔ Installed 1 packages
✔ Linked 80 latest versions
[1/2] scripts.postinstall electron@8.0.1 › @electron/get@1.7.6 › global-agent@2.1.8 › core-js@^3.6.4 run "node -e \"try{require('./postinstall')}catch(e){}\"", root: "/Users/apple/workspace/electron/electron-quick-start/node_modules/_core-js@3.6.4@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[1/2] scripts.postinstall electron@8.0.1 › @electron/get@1.7.6 › global-agent@2.1.8 › core-js@^3.6.4 finished in 134ms
[2/2] scripts.postinstall electron@^8.0.0 run "node install.js", root: "/Users/apple/workspace/electron/electron-quick-start/node_modules/_electron@8.0.1@electron"
(node:5004) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://cdn.npm.taobao.org/dist/electron/v8.0.1/electron-v8.0.1-darwin-x64.zip
    at EventEmitter.<anonymous> (/Users/apple/workspace/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:321:20)
    at module.exports (/Users/apple/workspace/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/apple/workspace/electron/electron-quick-start/node_modules/_got@9.6.0@got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:333:22)
    at ClientRequest.origin.emit (/Users/apple/workspace/electron/electron-quick-start/node_modules/_@szmarczak_http-timer@1.1.2@@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
(node:5004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2/2] scripts.postinstall electron@^8.0.0 finished in 3s
✔ Run 2 scripts
Recently updated (since 2020-02-12): 1 packages (detail see file /Users/apple/workspace/electron/electron-quick-start/node_modules/.recently_updates.txt)
✔ All packages installed (85 packages installed from npm registry, used 6s(network 3s), speed 72.26kB/s, json 81(214.25kB), tarball 0B)


use" npm start" can't start project
use "electron ."

**Comment by urscion** [comment]
The simplest way I found to fix this problem (for me) was to set the following environment variable
`ELECTRON_GET_USE_PROXY=<your proxy>`

This is documented in electron/get, but it's not exactly obvious/intuitive as I had http/https_proxy set in my environment but it did not use them.

**Comment by VishalAkhouri** [comment]
The only electron major version that seem to work for me is `"electron": "6.0.0"`. I have tried  "electron": "^7.1.7" and "electron": "^8.0.3".
It seems to infinitely stuck trying to do node install.js (from electron installed package)
```
> electron@6.0.0 postinstall /Users/XXX/XXX/electron-quick-start/node_modules/electron
> node install.js  
```

**Comment by caob1234** [comment]
This is indeed a network issue.I solved this problem by turning off the VPN and switching the network environment.

**Comment by tangyefei** [comment]
After use install cnpm and then run `cnpm install` it works.

**Comment by huoguozhang** [comment]
my mac still excute node install.js all day(see bottom), i  am use taobao mirro, i am at china,i guess network error, so, i want know others way,like just copy all file to /node_modules/electron
```
>electron@8.1.0 postinstall /Users/xxx/Desktop/electron-study/node_modules/electron
> node install.js
```
