### ISSUE TITLE
启动后页面报错

### ISSUE THREAD

**Issue by niuniugit** [electron/electron-quick-start#352]
ncaught Exception:
TypeError: mainWindow.loadFile is not a function
    at App.createWindow (/Users/sunan/Downloads/electron-quick-start-master/main.js:13:14)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)

**Comment by PeterlitsZo** [comment]
I think it is better if you leave a message by English but not Chinese...

启动后页面报错 means: After start it, it throw some error.

**Comment by yanabcd** [comment]
so many bug，and no “window.open” in this document，shit，how can i open a new window in this software,a lot of time be waste! and tray, you kown tray? it's failed. i'm so sad, why i can't be a genius? god who can help me,what's mean in this world.

**Comment by PeterlitsZo** [comment]
> n this document，shit，how can i open a new window in this software,a lot of time be waste! and tray, you kown tray? it's failed. i'm so

Well, what happen on you? Try to be easy...
