### ISSUE TITLE
'whenready' doesn't exist 

### ISSUE THREAD

**Issue by Maxsteel91Dev** [electron/electron-quick-start#370]
Hello, I wanted to test electron but when I launch it I have an error:

```
D:\Users\USER0\Documents\NodeJS Projects\test\main.js:25
app.whenReady().then(createWindow)
    ^

TypeError: Cannot read property 'whenReady' of undefined
    at Object.<anonymous> (D:\Users\USER0\Documents\NodeJS Projects\radiocontroll\main.js:25:5)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)?[39m
?[90m    at internal/main/run_main_module.js:18:47?[39m
```
 Code: 

```
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```
my package.json

```
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^8.2.0"
  }
}
```

NodeJS version: v12.16.1

Thanks for help me.

**Comment by Wexion** [comment]
try this:
`const {app, BrowserWindow} = require('electron');
const path = require('path');`

I think you are missing semi colons. It worked for me.

**Comment by Human489** [comment]
Did you run `npm install && npm start`, because I got the same error when only running `npm start`

**Comment by codebytere** [comment]
@Maxsteel91Dev you need to run both `npm install` and `npm start` as stated above. it should work then.
