### ISSUE TITLE
[Error] After start it throw error like `Electron failed to install correctly'

### ISSUE THREAD

**Issue by PeterlitsZo** [electron/electron-quick-start#379]
Hello everyone, It looks like #212 but it is helpless for me, I try to uninstall and install for many times but it is not work at all.

The error message is below:

``` shell
 > electron-quick-start@1.0.0 start /home/peter/proj/electron-quick-start
 > electron .
 
 /home/peter/proj/electron-quick-start/node_modules/electron/index.js:14
     throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
     ^   
 
 Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
     at getElectronPath (/home/peter/proj/electron-quick-start/node_modules/electron/index.js:14:11)
     at Object.<anonymous> (/home/peter/proj/electron-quick-start/node_modules/electron/index.js:18:18)
     at Module._compile (internal/modules/cjs/loader.js:689:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
     at Module.load (internal/modules/cjs/loader.js:599:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
     at Module.require (internal/modules/cjs/loader.js:637:17)
     at require (internal/modules/cjs/helpers.js:22:18)
     at Object.<anonymous> (/home/peter/proj/electron-quick-start/node_modules/electron/cli.js:3:16)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! electron-quick-start@1.0.0 start: `electron .`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the electron-quick-start@1.0.0 start script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in: 
 npm ERR!     /home/peter/.npm/_logs/2020-05-06T17_39_39_449Z-debug.log
 ```

And I think maybe this is helpful:

``` shell
$ node -v
v10.15.2
$ npm -v
6.14.5
```

That is all, thanks. (Will someone help me? Please ~)

**Comment by PeterlitsZo** [comment]
By the way, I run it under `GUN/Linux Debian`.

Thanks a lot `>_<`

**Comment by PeterlitsZo** [comment]
Hello all, I found that the electron need run `node node_module/electron/install.js` after install. But it is going to throw a error with message like this:
``` shell
(node:4348) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo ENOTFOUND github.com github.com:443                                                                          
 at ClientRequest.request.once.error (/home/peter/proj/electron-quick-start/node_modules/got/source/request-as-event-emitter.js:178:14)
 at Object.onceWrapper (events.js:277:13)
 at ClientRequest.emit (events.js:194:15)
 at ClientRequest.origin.emit.args (/home/peter/proj/electron-quick-start/node_modules/@szmarczak/http-timer/source/index.js:37:11)
 at TLSSocket.socketErrorListener (_http_client.js:392:9)
 at TLSSocket.emit (events.js:189:13)
 at emitErrorNT (internal/streams/destroy.js:82:8)
 at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
 at process._tickCallback (internal/process/next_tick.js:63:19)
 (node:4348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by          rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:4348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process      with a non-zero exit code.
```
It looks it can not content with `github.com:443`, what can I do for it?

**Comment by PeterlitsZo** [comment]
This is the success way: change the `virtual box` (yes I run the linux under a Box) network setting:
form Host-only network to NAT.
(But why? why `NAT` can make it download but `Host-only` cannot? `Host-only` can help me to browse google, but cannot download, `NAT` cannot let me browse google but can help me download the resource?)

**Comment by codebytere** [comment]
Closing as this is a system issue and not an issue with Electron itself. Glad you figured it out.

**Comment by PeterlitsZo** [comment]
You are welcome `>_<`
