### ISSUE TITLE
npm start  errno 3221225477

### ISSUE THREAD

**Issue by denglai** [electron/electron-quick-start#388]
electron:v9.0.0
node:v12.14.1

i have a require(demo.node) file, file need node10.15.1, i npm run ./node_modules/.bin/electron-rebuild,  

$ npm start

> electron-quick-start@1.0.0 start F:\ceshi_demo\electron-quick-start
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\houyu1\AppData\Roaming\npm-cache\_logs\2020-05-21T08_33_01_075Z-debug.log
/c/Program Files/nodejs/npm: line 37:  1560 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"

**Comment by poumason** [comment]
I also can't start the example.
following is my log:
```
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle first_app@1.0.0~prestart: first_app@1.0.0
6 info lifecycle first_app@1.0.0~start: first_app@1.0.0
7 verbose lifecycle first_app@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle first_app@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\pouma\source\electrol_sample\first_app\node_modules\.bin;C:\Users\pouma\bin;C:\Program Files\git\usr\local\bin;C:\Program Files\git\usr\bin;C:\Program Files\git\usr\bin;C:\Program Files\git\opt\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs;C:\Users\pouma\AppData\Local\Microsoft\WindowsApps;C:\Users\pouma\AppData\Local\Programs\Microsoft VS Code\bin;C:\flutter\bin;C:\Users\pouma\.dotnet\tools;C:\Users\pouma\AppData\Roaming\npm;C:\Users\pouma\AppData\Local\Programs\Fiddler;C:\Users\pouma\AppData\Local\Microsoft\WindowsApps;C:\Program Files\git\usr\bin\vendor_perl;C:\Program Files\git\usr\bin\core_perl
9 verbose lifecycle first_app@1.0.0~start: CWD: C:\Users\pouma\source\electrol_sample\first_app
10 silly lifecycle first_app@1.0.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle first_app@1.0.0~start: Returned: code: 2147483651  signal: null
12 info lifecycle first_app@1.0.0~start: Failed to exec start script
13 verbose stack Error: first_app@1.0.0 start: `electron .`
13 verbose stack Exit status 2147483651
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by poumason** [comment]
https://github.com/electron/electron/issues/23753
I reference the issue and change electron version is 8.2.0. the issue be solved.

**Comment by ckerr** [comment]
> [electron/electron#23753](https://github.com/electron/electron/issues/23753) I reference the issue and change electron version is 8.2.0. the issue be solved.

Closing this issue as it's reported solved.
