### ISSUE TITLE
start error on win10 x64

### ISSUE THREAD

**Issue by foxundermoon** [electron/electron-quick-start#39]
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Server\\nodejs\\node.exe" "D:\\Server\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by jlord** [comment]
Do you have to type `D:\Server\nodejs\node.exe` to use Node? Or can you type `node -v` and get the version number?

You'll need Node on your `$PATH` to run this, which is normally set up when installing Node but perhaps something different happened in your case?

**Comment by foxundermoon** [comment]
@jlord   i'm re install the node node is on my `PATH`  
`node -v   
v5.10.0`
```
npm verb stack Error: electron-prebuilt@0.36.12 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (D:\Server\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at EventEmitter.emit (events.js:185:7)
npm verb stack     at ChildProcess.<anonymous> (D:\Server\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:850:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid electron-prebuilt@0.36.12
npm verb cwd H:\workspace\web\proxy\betwixt
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Server\\nodejs\\node.exe" "D:\\Server\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbo
se"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     H:\workspace\web\proxy\betwixt\npm-debug.log
```

**Comment by jlord** [comment]
This may actually be an `electron-prebuilt` issue. Can you try re-installing the latest version of quick start which uses the latest version.

**Comment by zhangolve** [comment]
I also have the start error but my system is win10 x32.

**Comment by jlord** [comment]
@zhangolve would you be able to post your output as well, please?

**Comment by jlord** [comment]
I am able to install and `npm start` successfully in my VM

- Windows 10 Pro 64
- Node 4.5.0

![npmstart](https://cloud.githubusercontent.com/assets/1305617/18322232/9488306a-74e6-11e6-9c8b-df9129e94368.png)

@zhangolve What version Node are you using? 

Has anyone re-run `npm install` and had better luck?

**Comment by jlord** [comment]
I also just tested this again after installing Node 6.5.0 and it works 😕 My only suggestion now is just to try deleting the `node_modules` folder and re-installing with `npm install`. Let me know if you try this.

**Comment by zhangolve** [comment]
@jlord  sorrry  reply to you so late . For some reason ,I changed to another computer and the computer's os is win7 ,and can't test the problem in my older  computer  immediately .but anyway thank you ,I will receive your suggestion and consider it sincerely.

**Comment by zeke** [comment]
Gonna close this out. Feel free to comment if the issue persists.
