### ISSUE TITLE
problems getting started on mac os x

### ISSUE THREAD

**Issue by cpg** [electron/electron-quick-start#49]
Hi, I'm having trouble with the quickstart. Prior to this I did a ``brew update`` and ``brew upgrade npm``.

I'm new to node/npm.

Any suggestions as to what is going wrong here?

```
$ npm install && npm start
npm http GET https://registry.npmjs.org/electron-prebuilt
npm http 304 https://registry.npmjs.org/electron-prebuilt
npm ERR! Error: No compatible version found: electron-prebuilt@'^0.37.8'
npm ERR! Valid install targets:
npm ERR! ["0.24.0","0.25.0","0.25.1","0.25.1-1","0.25.2","0.25.2-1","0.25.3","0.25.3-1","0.25.3-2","0.26.0","0.26.1","0.27.0","0.27.1","0.27.2","0.27.3","0.28.0","0.28.1","0.28.2","0.28.3","0.29.0","0.29.1","0.29.2","0.30.0","0.30.1","0.30.2","0.30.3","0.30.4","0.30.5","0.31.0","0.30.6","0.31.1","0.31.2","0.32.0","0.32.1","0.32.2","0.32.3","0.33.0","0.33.1","0.30.7","0.33.2","0.30.8","0.33.3","0.33.4","0.33.5","0.33.6","0.33.7","0.33.8","0.33.9","0.34.0","0.34.1","0.34.2","0.34.3","0.35.0","0.35.1","0.34.4","0.34.5","0.35.2","0.35.3","0.35.4","0.36.0","0.36.1","0.36.2","0.35.5","0.36.3","0.35.6","0.36.4","0.36.5","0.36.6","0.36.7","0.36.8","0.36.9","0.36.10","0.36.11","0.37.0","0.37.1","0.37.2","0.36.12","0.37.3","0.37.4","0.37.5","0.37.6","0.37.7","0.37.8"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/cpg/work/160508-testing-electron/electron-quick-start
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cpg/work/160508-testing-electron/electron-quick-start/npm-debug.log
npm ERR! not ok code 0
```

and the details are

```
$ cat /Users/cpg/work/160508-testing-electron/electron-quick-start/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.2.18
3 info using node@v0.10.5
4 verbose read json /Users/cpg/work/160508-testing-electron/electron-quick-start/package.json
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ '/Users/cpg/work/160508-testing-electron/electron-quick-start',
6 verbose install   [ 'electron-prebuilt' ] ]
7 verbose from cache /Users/cpg/work/160508-testing-electron/electron-quick-start/package.json
8 info preinstall electron-quick-start@1.0.0
9 verbose from cache /Users/cpg/work/160508-testing-electron/electron-quick-start/package.json
10 verbose readDependencies using package.json deps
11 verbose cache add [ 'electron-prebuilt@^0.37.8', null ]
12 verbose cache add name=undefined spec="electron-prebuilt@^0.37.8" args=["electron-prebuilt@^0.37.8",null]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: 'electron-prebuilt@^0.37.8',
13 verbose parsed url   path: 'electron-prebuilt@^0.37.8',
13 verbose parsed url   href: 'electron-prebuilt@^0.37.8' }
14 verbose cache add name="electron-prebuilt" spec="^0.37.8" args=["electron-prebuilt","^0.37.8"]
15 verbose parsed url { protocol: null,
15 verbose parsed url   slashes: null,
15 verbose parsed url   auth: null,
15 verbose parsed url   host: null,
15 verbose parsed url   port: null,
15 verbose parsed url   hostname: null,
15 verbose parsed url   hash: null,
15 verbose parsed url   search: null,
15 verbose parsed url   query: null,
15 verbose parsed url   pathname: '^0.37.8',
15 verbose parsed url   path: '^0.37.8',
15 verbose parsed url   href: '^0.37.8' }
16 verbose addNamed [ 'electron-prebuilt', '^0.37.8' ]
17 verbose addNamed [ null, null ]
18 silly lockFile b4ec6c31-electron-prebuilt-0-37-8 electron-prebuilt@^0.37.8
19 verbose lock electron-prebuilt@^0.37.8 /Users/cpg/.npm/b4ec6c31-electron-prebuilt-0-37-8.lock
20 info addNameTag [ 'electron-prebuilt', '^0.37.8' ]
21 verbose url raw electron-prebuilt
22 verbose url resolving [ 'https://registry.npmjs.org/', './electron-prebuilt' ]
23 verbose url resolved https://registry.npmjs.org/electron-prebuilt
24 info trying registry request attempt 1 at 10:24:48
25 verbose etag "3DIBHBR4X0OIT00V4DGTI8X2C"
26 http GET https://registry.npmjs.org/electron-prebuilt
27 http 304 https://registry.npmjs.org/electron-prebuilt
28 silly registry.get cb [ 304,
28 silly registry.get   { date: 'Sun, 08 May 2016 17:24:35 GMT',
28 silly registry.get     via: '1.1 varnish',
28 silly registry.get     'cache-control': 'max-age=300',
28 silly registry.get     etag: '"3DIBHBR4X0OIT00V4DGTI8X2C"',
28 silly registry.get     age: '173',
28 silly registry.get     connection: 'keep-alive',
28 silly registry.get     'x-served-by': 'cache-dfw1831-DFW',
28 silly registry.get     'x-cache': 'HIT',
28 silly registry.get     'x-cache-hits': '1',
28 silly registry.get     'x-timer': 'S1462728275.635401,VS0,VE0',
28 silly registry.get     vary: 'Accept-Encoding' } ]
29 verbose etag electron-prebuilt from cache
30 silly lockFile b4ec6c31-electron-prebuilt-0-37-8 electron-prebuilt@^0.37.8
31 silly lockFile b4ec6c31-electron-prebuilt-0-37-8 electron-prebuilt@^0.37.8
32 error Error: No compatible version found: electron-prebuilt@'^0.37.8'
32 error Valid install targets:
32 error ["0.24.0","0.25.0","0.25.1","0.25.1-1","0.25.2","0.25.2-1","0.25.3","0.25.3-1","0.25.3-2","0.26.0","0.26.1","0.27.0","0.27.1","0.27.2","0.27.3","0.28.0","0.28.1","0.28.2","0.28.3","0.29.0","0.29.1","0.29.2","0.30.0","0.30.1","0.30.2","0.30.3","0.30.4","0.30.5","0.31.0","0.30.6","0.31.1","0.31.2","0.32.0","0.32.1","0.32.2","0.32.3","0.33.0","0.33.1","0.30.7","0.33.2","0.30.8","0.33.3","0.33.4","0.33.5","0.33.6","0.33.7","0.33.8","0.33.9","0.34.0","0.34.1","0.34.2","0.34.3","0.35.0","0.35.1","0.34.4","0.34.5","0.35.2","0.35.3","0.35.4","0.36.0","0.36.1","0.36.2","0.35.5","0.36.3","0.35.6","0.36.4","0.36.5","0.36.6","0.36.7","0.36.8","0.36.9","0.36.10","0.36.11","0.37.0","0.37.1","0.37.2","0.36.12","0.37.3","0.37.4","0.37.5","0.37.6","0.37.7","0.37.8"]
32 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
32 error     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
32 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
32 error     at Object.oncomplete (fs.js:107:15)
33 error If you need help, you may report this log at:
33 error     <http://github.com/isaacs/npm/issues>
33 error or email it to:
33 error     <npm-@googlegroups.com>
34 error System Darwin 15.4.0
35 error command "node" "/usr/local/bin/npm" "install"
36 error cwd /Users/cpg/work/160508-testing-electron/electron-quick-start
37 error node -v v0.10.5
38 error npm -v 1.2.18
39 verbose exit [ 1, true ]
```

**Comment by pjotrsavitski** [comment]
I might be wrong, but [getting started](http://electron.atom.io/#get-started) page and [.node-version](https://github.com/electron/electron/blob/master/.node-version) file from the repository suggest that 5.10.0 might be the currently used one.

These logs clearly indicate that you are running an ancient version of node. Consider using [nvm](https://github.com/creationix/nvm) or anything else you like to make sure you have the correct version to get the job done.

**Comment by jlord** [comment]
Yep, your versions of Node and npm are very out of date and don't support things like the `^` being used in the `package.json` in this project. 

Closing out, upgrading Node should fix this 👍
