### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by cjdg** [electron/electron-quick-start#53]
Ubuntu 16.04x64
Node 6.10

> electron-quick-start@1.0.0 start /home/cjdg/Escritorio/Electron/electron-quick-start
> electron main.js

App threw an error when running [TypeError: Cannot read property 'on' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/home/cjdg/Escritorio/Electron/electron-quick-start/main.js:33:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/home/cjdg/Escritorio/Electron/electron-quick-start/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/home/cjdg/Escritorio/Electron/electron-quick-start/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by jlord** [comment]
@cjdg Have you edited the `main.js` file at all? Can you share what line 33 is?

**Comment by kevinsawicki** [comment]
I believe this has been fixed in Electron 1.1.2 so I'm going to close this out.
