### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by VitoFanelli** [electron/electron-quick-start#560]
Hi, i clone the repository and change directory but when i run npm install by windows command prompt i get this errror

npm ERR! path C:\Users\vitof\electron-quick-start\node_modules\electron
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: read ECONNRESET
npm ERR!     at ClientRequest.<anonymous> (C:\Users\vitof\electron-quick-start\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:510:26)
npm ERR!     at ClientRequest.emit (node:events:402:35)
npm ERR!     at ClientRequest.origin.emit (C:\Users\vitof\electron-quick-start\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:390:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

Can you help me?

Thank you!

**Comment by trty** [comment]
HI, I also encountered this problem in window, Maybe you can try switching source

**Comment by trasherdk** [comment]
I'm running in Git `bash` with no problem:
```sh
admin@ACER-64BIT MINGW64 /c/Workspace/Github/electron-quick-start (master)
$ node -v && npm -v
v16.13.1
8.3.0
```
and
```sh
$ npm install

up to date, audited 87 packages in 2s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by UTrawiecki** [comment]
Try
`npm i --save-dev --production electron`

**Comment by ashutoshbhadoria** [comment]
In windows system you can use this workaround.

- Powershell
```ps1
$env:NODE_TLS_REJECT_UNAUTHORIZED=0
```

- CMD
```bat
 set NODE_TLS_REJECT_UNAUTHORIZED=0
```

> Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

**Comment by arya-vats** [comment]
@VitoFanelli  I would like to work on this issue, can you please assign it to me?

**Comment by erickzhao** [comment]
@arya-vats I don't think there's an active task to work on with this issue.

**Comment by arya-vats** [comment]
Well i was just trying to fix the old node modules that haven't been updated .

**Comment by erickzhao** [comment]
>  fix the old node modules

Could you elaborate on this? I'm not sure I understand.

**Comment by LiangXixixi** [comment]
In China, it may be a problem with the ladder. I set the ladder as a global agent and then installed it normally.

**Comment by blade-demon** [comment]
In .npmrc config the following content:

ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"

then run`npm install`

**Comment by hsibin** [comment]
Don't use China mirror sources, such as: taobao

**Comment by Llldmiao** [comment]
> Don't use China mirror sources, such as: taobao

this works for me.

**Comment by srorupal** [comment]
Hi, I'm facing with below error. Could anyone provide the solution.
verbose stack Error: command failed
16113 verbose stack     at ChildProcess.<anonymous> (C:\Users\AppData\Roaming\nvm\v18.17.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
16113 verbose stack     at ChildProcess.emit (node:events:514:28)
16113 verbose stack     at maybeClose (node:internal/child_process:1091:16)
16113 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
16114 verbose pkgid pjs@3.1.0
16115 verbose cwd C:\Users\Desktop\perseus
16116 verbose Windows_NT 10.0.22621

**Comment by ashutosh017** [comment]
> In windows system you can use this workaround.
> 
> * Powershell
> 
> ```powershell
> $env:NODE_TLS_REJECT_UNAUTHORIZED=0
> ```
> 
> * CMD
> 
> ```batchfile
>  set NODE_TLS_REJECT_UNAUTHORIZED=0
> ```
> 
> > Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

Great! It worked!
