### ISSUE TITLE
when  update electron to  ^20.0.0 ,npm install fail 

### ISSUE THREAD

**Issue by yuerdev** [electron/electron-quick-start#626]
```
sudo pnpm i 
Packages: +79
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/.pnpm/electron@20.0.1/node_modules/electron: Running postinstall script, failed in 2m 11.1s
.../node_modules/electron postinstall$ node install.js
│ RequestError: read ETIMEDOUT
│     at ClientRequest.<anonymous> (/Users/jacky/rock/electron-quick-start/node_modules/.pnpm/got@9.6.0/node_modules/got/source/request-as-event-emitter.js:178:14)
│     at Object.onceWrapper (node:events:510:26)
│     at ClientRequest.emit (node:events:402:35)
│     at ClientRequest.origin.emit (/Users/jacky/rock/electron-quick-start/node_modules/.pnpm/@szmarczak+http-timer@1.1.2/node_modules/@szmarczak/http-timer/source/index.js:37:11)
│     at TLSSocket.socketErrorListener (node:_http_client:447:9)
│     at TLSSocket.emit (node:events:390:28)
│     at emitErrorNT (node:internal/streams/destroy:157:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
└─ Failed in 2m 11.1s
Progress: resolved 80, reused 79, downloaded 0, added 0, done
 ELIFECYCLE  Command failed with exit code 1.
```
node version :16.13.2
pnpm version: 7.6.0

**Comment by yuerdev** [comment]
if i use `npm i` throw errror
```
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jacky/.npm/_logs/2022-08-04T03_18_56_211Z-debug-0.log
```

**Comment by BhinbahadurUK** [comment]
Rewrite from basic scratch rebuild , build online empty box HOLDING value
nothing to nothing average entry should open just before with blocks in
that ciphen block write for example pull to code extract build for name
sake example my name add U.K Bhinbahadur in exquisite pull link to
regenerate constants then come back to your side write to throw but
populate to the reformer picks you up then youl call me okay.

UK Bhinbahadur

**Comment by Lsnsh** [comment]
https://www.electronjs.org/docs/latest/tutorial/installation#custom-mirrors-and-caches
