### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string (Yarn pnp)

### ISSUE THREAD

**Issue by asamofal** [electron/electron-quick-start#680]
Hi there! Help me figure out where I'm wrong.
I'm trying to init a new VueJS project, according to VueJS docs I use recommended `create-vue` tool with yarn, then install `electron` there. But there's an error in yarn pnp mechanism. I'm not sure if is it really related to `electron` or to `create-vue`, or to `yarn` itself. 
Any ideas? 

[![asciicast](https://asciinema.org/a/ylqq3WeEzdxN7iNxDtr9lkrzG.svg)](https://asciinema.org/a/ylqq3WeEzdxN7iNxDtr9lkrzG)

![image](https://user-images.githubusercontent.com/2729547/210242087-4b2a9f7f-54af-42f1-9f30-9e2df611bf5b.png)
```
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:387:5)
at validateString (node:internal/validators:121:11)
at Object.normalize (node:path:1128:5)
at contains (/Volumes/code/pos/.pnp.cjs:3762:18)
at ppath.contains (/Volumes/code/pos/.pnp.cjs:3776:32)
at isPathIgnored (/Volumes/code/pos/.pnp.cjs:13259:27)
at findPackageLocator (/Volumes/code/pos/.pnp.cjs:13329:9)
at Object.findPackageLocator (/Volumes/code/pos/.pnp.cjs:13710:14)
at findApiPathFor (/Volumes/code/pos/.pnp.cjs:13801:41)
at Object.getApiPathFromParent (/Volumes/code/pos/.pnp.cjs:13852:36)
```
p.s. if create a project with `yarn init` - the test app launches fine =\

**Comment by asamofal** [comment]
Oh, sorry, I was wrong with the repo. 
This is definitely not related to `electron-quick-start`.
