### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by Teejay128** [electron/electron-quick-start#705]
I copied the command for running this repo and pasted it in my terminal

but it throws this error when it gets to the `npm install` part
```
$ npm install
npm ERR! code 1
npm ERR! path C:\Users\Dayo\Desktop\NODE\electron-quick-start\node_modules\electron
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: getaddrinfo ENOTFOUND github.com
npm ERR!     at ClientRequest.<anonymous> (C:\Users\Dayo\Desktop\NODE\electron-quick-start\node_modules\got\dist\source\core\index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:640:26)
npm ERR!     at ClientRequest.emit (node:events:532:35)
npm ERR!     at ClientRequest.origin.emit (C:\Users\Dayo\Desktop\NODE\electron-quick-start\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:520:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dayo\AppData\Local\npm-cache\_logs\2023-01-27T14_16_18_899Z-debug-0.log
```

It may have something to do with the comments in the instructions

``` CLI
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```
Not sure if removing them would solve the issue

**Comment by codebytere** [comment]
> RequestError: getaddrinfo ENOTFOUND github.com

this is a proxy or internet issue, not an issue with Electron. See https://forum.snapcraft.io/t/electron-7-and-above-fails-to-install-with-getaddrinfo-enotfound-github-com-on-launchpad-build-snapcraft-io/20432 for reference.
